import { ItemRarity, ItemType } from "../items/Item";
import type { MaterialDefinition } from "./Material";
import { MaterialCategory } from "./MaterialCategory";

export const MATERIAL_DATA = {
    MYSTIC_IRON: {
        id: "mystic_iron",
        name: "Huyền Thiết",
        description: "Khoáng thạch cứng chắc dùng để luyện chế trang bị.",
        type: ItemType.MATERIAL,
        rarity: ItemRarity.COMMON,
        stackable: true,
        maxStack: 999,
        materialCategory: MaterialCategory.ORE,
        tier: 1,
    },
    SPIRIT_WOOD: {
        id: "spirit_wood",
        name: "Linh Mộc",
        description: "Linh mộc chứa tinh hoa thiên địa.",
        type: ItemType.MATERIAL,
        rarity: ItemRarity.COMMON,
        stackable: true,
        maxStack: 999,
        materialCategory: MaterialCategory.ESSENCE,
        tier: 1,
    },
    SPIRIT_HERB: {
        id: "spirit_herb",
        name: "Linh Thảo",
        description: "Linh thảo chứa một lượng linh khí nhỏ.",
        type: ItemType.MATERIAL,
        rarity: ItemRarity.COMMON,
        stackable: true,
        maxStack: 999,
        materialCategory: MaterialCategory.HERB,
        tier: 1,
    },
    BLOOD_SPIRIT_FLOWER: {
        id: "blood_spirit_flower",
        name: "Huyết Linh Hoa",
        description: "Dược liệu sinh trưởng gần nơi yêu thú tụ tập.",
        type: ItemType.MATERIAL,
        rarity: ItemRarity.UNCOMMON,
        stackable: true,
        maxStack: 999,
        materialCategory: MaterialCategory.HERB,
        tier: 1,
    },
    WOLF_FANG: {
        id: "wolf_fang",
        name: "Lang Nha",
        description: "Nanh sắc của yêu lang, thích hợp làm vật liệu luyện khí.",
        type: ItemType.MATERIAL,
        rarity: ItemRarity.COMMON,
        stackable: true,
        maxStack: 999,
        materialCategory: MaterialCategory.MONSTER,
        tier: 1,
    },
    MONSTER_CORE: {
        id: "monster_core",
        name: "Yêu Đan",
        description: "Nội đan tích tụ yêu lực của yêu thú.",
        type: ItemType.MATERIAL,
        rarity: ItemRarity.UNCOMMON,
        stackable: true,
        maxStack: 999,
        materialCategory: MaterialCategory.MONSTER,
        tier: 1,
    },
    MONSTER_BLOOD_ESSENCE: {
        id: "monster_blood_essence",
        name: "Tinh Huyết Yêu Thú",
        description: "Tinh huyết cô đọng mang yêu lực tinh thuần.",
        type: ItemType.MATERIAL,
        rarity: ItemRarity.RARE,
        stackable: true,
        maxStack: 999,
        materialCategory: MaterialCategory.ESSENCE,
        tier: 1,
    },
    SPIRIT_ESSENCE: {
        id: "spirit_essence",
        name: "Tinh Hoa Linh Khí",
        description: "Tinh hoa linh khí còn lại trong cơ thể yêu thú.",
        type: ItemType.MATERIAL,
        rarity: ItemRarity.UNCOMMON,
        stackable: true,
        maxStack: 999,
        materialCategory: MaterialCategory.ESSENCE,
        tier: 1,
    },
    MONSTER_KING_CORE: {
        id: "monster_king_core",
        name: "Yêu Vương Nội Đan",
        description: "Nội đan quý hiếm chỉ có ở yêu vương.",
        type: ItemType.MATERIAL,
        rarity: ItemRarity.EPIC,
        stackable: true,
        maxStack: 999,
        materialCategory: MaterialCategory.BOSS,
        tier: 1,
    },
} as const satisfies Record<string, MaterialDefinition>;

export const MATERIAL_DEFINITIONS: ReadonlyArray<MaterialDefinition> =
    Object.values(MATERIAL_DATA);
