import {
    SkillEffectType,
    SkillTargetType,
} from "./Skill";
import type { SkillDefinition } from "./Skill";

export const SKILL_IDS = {
    NORMAL_SLASH: "normal-slash",
    SWORD_QI: "sword-qi",
    TEN_THOUSAND_SWORDS: "ten-thousand-swords",
    ORIGIN_RECOVERY: "heal",
    WIND_BLADE: "wind-blade",
    CHAIN_SLASH: "chain-slash",
    AZURE_SWORD_RAIN: "azure-sword-rain",
} as const;

export const SKILL_DATA: ReadonlyArray<SkillDefinition> = [
    {
        id: SKILL_IDS.NORMAL_SLASH,
        name: "Chém Thường",
        description: "Đòn kiếm cơ bản, không tiêu hao Khí.",
        mpCost: 0,
        baseCooldown: 0.85,
        targetType: SkillTargetType.SINGLE_ENEMY,
        effectType: SkillEffectType.DAMAGE,
        damageMultiplier: 1,
        range: 180,
        castTime: 0.22,
        animation: "slash",
        icon: "/assets/skills/normal-slash/icon/icon.png",
        vfxProfile: "normal-slash",
        progression: {
            maxLevel: 10,
            upgradeCostBase: 25,
            upgradeCostGrowth: 1.45,
            damageMultiplierPerLevel: 0.06,
            cooldownPerLevel: -0.015,
        },
    },
    {
        id: SKILL_IDS.SWORD_QI,
        name: "Kiếm Khí",
        description: "Kiếm khí cân bằng giữa sát thương, Khí và hồi chiêu.",
        mpCost: 10,
        baseCooldown: 4,
        targetType: SkillTargetType.SINGLE_ENEMY,
        effectType: SkillEffectType.DAMAGE,
        damageMultiplier: 1.6,
        range: 900,
        castTime: 0.28,
        animation: "spell",
        icon: "/assets/skills/sword-qi/icon/icon.png",
        vfxProfile: "sword-qi",
        progression: {
            maxLevel: 10,
            upgradeCostBase: 45,
            upgradeCostGrowth: 1.5,
            damageMultiplierPerLevel: 0.12,
            mpCostPerLevel: -0.35,
            cooldownPerLevel: -0.08,
        },
    },
    {
        id: SKILL_IDS.TEN_THOUSAND_SWORDS,
        name: "Vạn Kiếm Trận",
        description: "AOE ổn định để dọn nhiều quái cùng lúc.",
        mpCost: 20,
        baseCooldown: 8,
        targetType: SkillTargetType.ALL_ENEMIES,
        effectType: SkillEffectType.DAMAGE,
        damageMultiplier: 1,
        range: 900,
        castTime: 0.45,
        animation: "spell",
        icon: "/assets/skills/ten-thousand-swords/icon/icon.png",
        vfxProfile: "ten-thousand-swords",
        progression: {
            maxLevel: 10,
            upgradeCostBase: 70,
            upgradeCostGrowth: 1.52,
            damageMultiplierPerLevel: 0.1,
            mpCostPerLevel: -0.45,
            cooldownPerLevel: -0.12,
        },
    },
    {
        id: SKILL_IDS.ORIGIN_RECOVERY,
        name: "Hồi Nguyên Thuật",
        description: "Hồi phục bản thân, ưu tiên build sống sót.",
        mpCost: 15,
        baseCooldown: 12,
        targetType: SkillTargetType.SELF,
        effectType: SkillEffectType.HEAL,
        healPercent: 0.2,
        castTime: 0.35,
        animation: "spell",
        icon: "/assets/skills/heal/icon/icon.png",
        vfxProfile: "heal",
        progression: {
            maxLevel: 10,
            upgradeCostBase: 65,
            upgradeCostGrowth: 1.52,
            healPercentPerLevel: 0.025,
            mpCostPerLevel: -0.4,
            cooldownPerLevel: -0.18,
        },
    },
    {
        id: SKILL_IDS.WIND_BLADE,
        name: "Phong Nhận",
        description: "Kiếm khí nhanh, thiên về DPS đơn mục tiêu.",
        mpCost: 12,
        baseCooldown: 2.8,
        targetType: SkillTargetType.SINGLE_ENEMY,
        effectType: SkillEffectType.DAMAGE,
        damageMultiplier: 1.25,
        range: 900,
        castTime: 0.22,
        animation: "spell",
        icon: "/assets/skills/sword-qi/icon/icon.png",
        vfxProfile: "sword-qi",
        progression: {
            maxLevel: 10,
            upgradeCostBase: 80,
            upgradeCostGrowth: 1.55,
            damageMultiplierPerLevel: 0.1,
            mpCostPerLevel: -0.3,
            cooldownPerLevel: -0.1,
        },
    },
    {
        id: SKILL_IDS.CHAIN_SLASH,
        name: "Liên Trảm",
        description: "Đòn cận chiến nặng, ít tốn Khí, sát thương cao.",
        mpCost: 6,
        baseCooldown: 2.2,
        targetType: SkillTargetType.SINGLE_ENEMY,
        effectType: SkillEffectType.DAMAGE,
        damageMultiplier: 1.85,
        range: 210,
        castTime: 0.24,
        animation: "slash",
        icon: "/assets/skills/normal-slash/icon/icon.png",
        vfxProfile: "normal-slash",
        progression: {
            maxLevel: 10,
            upgradeCostBase: 110,
            upgradeCostGrowth: 1.58,
            damageMultiplierPerLevel: 0.15,
            mpCostPerLevel: -0.2,
            cooldownPerLevel: -0.06,
        },
    },
    {
        id: SKILL_IDS.AZURE_SWORD_RAIN,
        name: "Thanh Liên Kiếm Vũ",
        description: "AOE bùng nổ mạnh, đổi lại tiêu hao Khí cao.",
        mpCost: 28,
        baseCooldown: 7,
        targetType: SkillTargetType.ALL_ENEMIES,
        effectType: SkillEffectType.DAMAGE,
        damageMultiplier: 1.45,
        range: 900,
        castTime: 0.42,
        animation: "spell",
        icon: "/assets/skills/ten-thousand-swords/icon/icon.png",
        vfxProfile: "ten-thousand-swords",
        progression: {
            maxLevel: 10,
            upgradeCostBase: 160,
            upgradeCostGrowth: 1.6,
            damageMultiplierPerLevel: 0.14,
            mpCostPerLevel: -0.5,
            cooldownPerLevel: -0.12,
        },
    },
];

